pipeline:
  name: Code
  identifier: Code
  projectIdentifier: gh
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.iacmgithub
        repoName: pipeline_template
        build: <+input>
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: |-
                      echo "hello"

                      echo <+trigger.branch>
  variables:
    - name: input_variable
      type: String
      description: ""
      required: false
      value: <+input>
